export const PREUPGRADE_REPORTS_REQUEST = 'PREUPGRADE_REPORTS_REQUEST';
export const PREUPGRADE_REPORTS_SUCCESS = 'PREUPGRADE_REPORTS_SUCCESS';
export const PREUPGRADE_REPORTS_FAILURE = 'PREUPGRADE_REPORTS_FAILURE';
export const PREUPGRADE_REPORTS_REMEDIATE_ENTRIES_REQUEST =
  'PREUPGRADE_REPORTS_REMEDIATE_ENTRIES_REQUEST';
export const PREUPGRADE_REPORTS_REMEDIATE_ENTRIES_SUCCESS =
  'PREUPGRADE_REPORTS_REMEDIATE_ENTRIES_SUCCESS';
export const PREUPGRADE_REPORTS_REMEDIATE_ENTRIES_FAILURE =
  'PREUPGRADE_REPORTS_REMEDIATE_ENTRIES_FAILURE';
