export const PREUPGRADE_REPORTS_REQUEST = 'PREUPGRADE_REPORTS_REQUEST';
export const PREUPGRADE_REPORTS_SUCCESS = 'PREUPGRADE_REPORTS_SUCCESS';
export const PREUPGRADE_REPORTS_FAILURE = 'PREUPGRADE_REPORTS_FAILURE';

